name: Laravel Package Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [ "11", "12" ]
        php: [ "8.2", "8.3" ]
        include:
          - laravel: "11"
            stability: "stable"
          - laravel: "12"
            stability: "stable"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl, bcmath, pdo, sqlite, fileinfo
        coverage: none

    - name: Create Laravel app
      run: |
        composer create-project laravel/laravel:^${{ matrix.laravel }} test-app ${{ matrix.stability }}
      env:
        COMPOSER_MEMORY_LIMIT: -1

    - name: Require package
      run: |
        cd test-app
        composer config repositories.local '{"type": "path", "url": "../", "options": {"symlink": true}}'
        composer require siberfx/turkiye-address:dev-main --dev
      env:
        COMPOSER_MEMORY_LIMIT: -1

    - name: Install test dependencies
      run: |
        cd test-app
        composer require --dev phpunit/phpunit ^10.0 --with-all-dependencies

    - name: Publish package assets
      run: |
        cd test-app
        php artisan turkiye:publish --migrations --seeders --force

    - name: Run migrations
      run: |
        cd test-app
        php artisan migrate --force

    - name: Run seeders
      run: |
        cd test-app
        php artisan db:seed --class=Database\\Seeders\\DatabaseSeeder

    - name: Run package tests
      run: |
        cd test-app
        ./vendor/bin/phpunit --testdox
