name: Laravel Package Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [ "11", "12" ]
        php: [ "8.2", "8.3" ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl, bcmath, pdo, sqlite, fileinfo
        coverage: none

    - name: Create Laravel app
      run: |
        composer create-project laravel/laravel:^${{ matrix.laravel }} test-app
      env:
        COMPOSER_MEMORY_LIMIT: -1

    - name: Require package
      run: |
        cd test-app
        composer config repositories.local '{"type": "path", "url": "../", "options": {"symlink": true}}'
        composer require siberfx/turkiye-address:dev-main
      env:
        COMPOSER_MEMORY_LIMIT: -1

    - name: Publish config and SQL dumps
      run: |
        cd test-app
        php artisan turkiye:publish-assets --force

    - name: Copy package files
      run: |
        rsync -a --exclude='test-app' ./ test-app/packages/turkiye-adresler-json/
      shell: bash

    - name: Run package tests
      run: |
        cd test-app
        php artisan vendor:publish --all
        ./vendor/bin/phpunit ../packages/turkiye-adresler-json/tests
